version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management

    ports:
    - '5672:5672'
    - '15672:15672'

    volumes:
      - 'rabbitmq_data:/var/lib/rabbitmq'


    environment:
      RABBITMQ_DEFAULT_USER: 'user'
      RABBITMQ_DEFAULT_PASS: 'password'



volumes:
  rabbitmq_data:
    driver: local